const lettersData = [
  { yezidi: "𐺀", kurmanji: "A", arabic: "ألف", audio: "audio/letter_elif.mp3" },
  { yezidi: "𐺁", kurmanji: "B", arabic: "باء", audio: "audio/letter_be.mp3" },
  { yezidi: "𐺂", kurmanji: "P", arabic: "باء مشددة (پ)", audio: "audio/letter_pe.mp3" },
  { yezidi: "𐺃", kurmanji: "P'", arabic: "باء انفجارية", audio: "audio/letter_phe.mp3" },
  { yezidi: "𐺄", kurmanji: "T'", arabic: "تاء", audio: "audio/letter_the.mp3" },
  { yezidi: "𐺅", kurmanji: "S", arabic: "ثاء / سين", audio: "audio/letter_se.mp3" },
  { yezidi: "𐺆", kurmanji: "C", arabic: "جيم (ج)", audio: "audio/letter_cim.mp3" },
  { yezidi: "𐺇", kurmanji: "Ç", arabic: "تشاء (چ)", audio: "audio/letter_chim.mp3" },
  { yezidi: "𐺈", kurmanji: "C'", arabic: "تشاء مشددة", audio: "audio/letter_chhim.mp3" },
  { yezidi: "𐺉", kurmanji: "H'", arabic: "حاء", audio: "audio/letter_hha.mp3" },
  { yezidi: "𐺊", kurmanji: "X", arabic: "خاء", audio: "audio/letter_xa.mp3" },
  { yezidi: "𐺋", kurmanji: "D", arabic: "دال", audio: "audio/letter_dal.mp3" },
  { yezidi: "𐺌", kurmanji: "Z", arabic: "ذال", audio: "audio/letter_zal.mp3" },
  { yezidi: "𐺍", kurmanji: "R", arabic: "راء مخففة", audio: "audio/letter_ra.mp3" },
  { yezidi: "𐺎", kurmanji: "R'", arabic: "راء مفخمة", audio: "audio/letter_rha.mp3" },
  { yezidi: "𐺏", kurmanji: "Z", arabic: "زاء", audio: "audio/letter_za.mp3" },
  { yezidi: "𐺐", kurmanji: "J", arabic: "جيم غير معطشة (ژ)", audio: "audio/letter_ja.mp3" },
  { yezidi: "𐺑", kurmanji: "S", arabic: "سين", audio: "audio/letter_sin.mp3" },
  { yezidi: "𐺒", kurmanji: "Ş", arabic: "شين", audio: "audio/letter_shin.mp3" },
  { yezidi: "𐺓", kurmanji: "Ş'", arabic: "صاد", audio: "audio/letter_sad.mp3" },
  { yezidi: "𐺔", kurmanji: "D", arabic: "ضاد", audio: "audio/letter_dad.mp3" },
  { yezidi: "𐺕", kurmanji: "T", arabic: "طاء", audio: "audio/letter_ta.mp3" },
  { yezidi: "𐺖", kurmanji: "Z'", arabic: "ظاء", audio: "audio/letter_ze.mp3" },
  { yezidi: "𐺗", kurmanji: "E'", arabic: "عين", audio: "audio/letter_eyn.mp3" },
  { yezidi: "𐺘", kurmanji: "X'", arabic: "غين", audio: "audio/letter_xheyn.mp3" },
  { yezidi: "𐺙", kurmanji: "F", arabic: "فاء", audio: "audio/letter_fa.mp3" },
  { yezidi: "𐺚", kurmanji: "V", arabic: "فاء ثلاثية (ڤ)", audio: "audio/letter_va.mp3" },
  { yezidi: "𐺛", kurmanji: "V", arabic: "واو / ڤ (شكل بديل)", audio: "audio/letter_va_alt.mp3" },
  { yezidi: "𐺜", kurmanji: "Q", arabic: "قاف", audio: "audio/letter_qaf.mp3" },
  { yezidi: "𐺝", kurmanji: "K", arabic: "كاف", audio: "audio/letter_kaf.mp3" },
  { yezidi: "𐺞", kurmanji: "K'", arabic: "كاف مشددة", audio: "audio/letter_khaf.mp3" },
  { yezidi: "𐺟", kurmanji: "G", arabic: "كاف مصرية (گ)", audio: "audio/letter_gaf.mp3" },
  { yezidi: "𐺠", kurmanji: "L", arabic: "لام", audio: "audio/letter_lam.mp3" },
  { yezidi: "𐺡", kurmanji: "M", arabic: "ميم", audio: "audio/letter_mim.mp3" },
  { yezidi: "𐺢", kurmanji: "N", arabic: "نون", audio: "audio/letter_nun.mp3" },
  { yezidi: "𐺣", kurmanji: "U", arabic: "ضمة / واو قصيرة", audio: "audio/letter_um.mp3" },
  { yezidi: "𐺤", kurmanji: "Û", arabic: "واو ممدودة", audio: "audio/letter_uum.mp3" },
  { yezidi: "𐺥", kurmanji: "W", arabic: "واو (W)", audio: "audio/letter_waw.mp3" },
  { yezidi: "𐺦", kurmanji: "O", arabic: "واو تفخيم (O)", audio: "audio/letter_ow.mp3" },
  { yezidi: "𐺧", kurmanji: "E", arabic: "فتحة / ألف قصيرة", audio: "audio/letter_ew.mp3" },
  { yezidi: "𐺨", kurmanji: "H", arabic: "هاء", audio: "audio/letter_hay.mp3" },
  { yezidi: "𐺩", kurmanji: "Y / Î", arabic: "ياء", audio: "audio/letter_yot.mp3" },
  { yezidi: "𐺪", kurmanji: "Ê", arabic: "ياء ممدودة", audio: "audio/letter_et.mp3" },
  { yezidi: "𐺰", kurmanji: "Ł", arabic: "لام مفخمة (مع نقطة فوق)", audio: "audio/letter_lam_dot.mp3" },
  { yezidi: "𐺱", kurmanji: "Ê", arabic: "ياء مع حركات تاريخية", audio: "audio/letter_yot_circumflex.mp3" }
];
